- name: Set httpd permission nginx
  become: true
  become_user: root
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Start nodejs
  become: true
  become_user: "{{ user }}"
  command:
    chdir: "/home/anna"
    cmd: "/usr/local/bin/pm2 start --name server {{ appPath }}"
