- name: add packages
  become: true
  become_user: root
  ansible.builtin.yum:
    name: "{{packages}}"

- name: add pm2
  become: true
  become_user: root
  npm:
    name: pm2
    global: yes
    state: latest
